### PR TITLE
Replace all occurences of JSON with JSONable

### PR DESCRIPTION
**Pull request by vjau**
In the meteor.d.ts, there are multiples occurences of the 'JSON' type.
I have looked everywhere what this type was about, only to find out that it's in the base Typescript definitions. 
However, 'JSON' refers to the ES5 JSON static object which tools are used to manipulate JSON data, and _not_ as intended by this definition file, as a way to refer to data that is JSONable.
So i have replaced all occurences of 'JSON' by the 'JSONable' interface, which was probably the original intent.

### CODE REVIEW

**Comment by vjau** [comment]
Probably modified wrong file, sorry.

**Comment by fullflavedave** [comment]
Thanks for catching this nuance.  I'll merge these changes, and then make the corresponding changes to the files used to generate meteor.d.ts.

**Comment by fullflavedave** [comment]
OK -- just let me know if you want me to modify the proper files.  The changes will either be generate-definition-files.js or meteor-manually-maintained-definitions.d.ts (but probably the former).

**Comment by vjau** [comment]
I don't know what to do with "'JSONCompatible': 'JSON'," in argTypeMapings.
I guess that it should be replaced by 'JSONCompatible:'JSONable" also ?
You can proceed to do the modifications or i will do them tomorrow.

**Comment by fullflavedave** [comment]
Yes.  What's on the left ('JSONCompatible') is what's in the meteor API.  What's on the right is what it should be changed to.  Makes me think we should just change the name "JSONable" to "JSONCompatible", or make JSONCompatible extend JSONable if there are other dependencies.  Then we could remove the mapping.

**Comment by fullflavedave** [comment]
I'll make the changes, and you can verify that meteor.d.ts turned out OK.

**Comment by fullflavedave** [comment]
I won't get to this until tomorrow morning (Pacific Standard Time) since I have some pressing work stuff right now, so if you get to it first, that's also fine.

**Pull request closed without merging**
