### PR TITLE
Readme.md updated for Windows usage

### PR DESCRIPTION
**Pull request by strake7**
Added insight for setup and usage on Windows

### CODE REVIEW

**Comment by fullflavedave** [comment]
Thanks a bunch for your contribution!

**Comment by strake7** [comment]
Of course. I would've expanded more on using meteor-typescript-compiler however I still haven't been able to get it to build with meteor yet. In the meantime ive just been using an visual studio code and running tsc

**Comment by fullflavedave** [comment]
I haven't tried the compiler recently, but it might be broken for Meteor 1.2, in which case we should do something about that.  I let WebStorm continuously transpile/build for me.  However, I think it might be time to try to create a TypeScript build transpiler plugin, just like there is for CoffeeScript, ES2015, LESS, SASS, etc. in Meteor.

**Comment by orefalo** [comment]
update coming soon ;-)

see https://github.com/barbatus/ts-compilers/issues/1#issuecomment-152334301 <https://github.com/barbatus/ts-compilers/issues/1#issuecomment-152334301>

**Comment by strake7** [comment]
Nice. Will definitely be looking for that update.

**Pull request merged**
